version: '3.4'

services:
  sample_dotnet:
    image: agussaepudin/sample-dot-net:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./certs:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
